In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv("C:/Users/galib/Downloads/archive (13)/job_salary_prediction_dataset.csv")

In [3]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

In [5]:
df["job_title"].unique()

array(['AI Engineer', 'Data Analyst', 'Frontend Developer',
       'Business Analyst', 'Product Manager', 'Backend Developer',
       'Machine Learning Engineer', 'DevOps Engineer',
       'Software Engineer', 'Cybersecurity Analyst', 'Data Scientist',
       'Cloud Engineer'], dtype=object)

In [6]:
df["education_level"].unique()

array(['Bachelor', 'PhD', 'High School', 'Diploma', 'Master'],
      dtype=object)

In [7]:
df["industry"].unique()

array(['Healthcare', 'Telecom', 'Media', 'Retail', 'Manufacturing',
       'Education', 'Finance', 'Technology', 'Consulting', 'Government'],
      dtype=object)

In [8]:
df["company_size"].unique()

array(['Medium', 'Small', 'Large', 'Enterprise', 'Startup'], dtype=object)

In [9]:
df["location"].unique()

array(['India', 'Australia', 'Singapore', 'Canada', 'Sweden', 'USA',
       'Netherlands', 'Remote', 'Germany', 'UK'], dtype=object)

In [10]:
df["remote_work"].unique()

array(['Hybrid', 'No', 'Yes'], dtype=object)

In [11]:
df.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [12]:
df.isnull().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [ ]:
sns.set_theme(style="whitegrid")
plt.figure(figsize=(10,6))
sns.histplot(df["salary"],kde=True,
            color="skyblue", bins=30)
plt.title("distribution of salaries", fontsize=15)
plt.xlabel("salary", fontsize=12)
plt.ylabel("frequency", fontsize=12)
plt.show()

In [ ]:
numerical_df=df.select_dtypes(include=["int64", "float64"])
corr_matrix=numerical_df.corr()
plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True,
           cmap="coolwarm", fmt=".2f",
           linewidths=.5)
plt.title("correlation heatmap of numericals features", fontsize=15)
plt.savefig("correlation_heatmap.png")

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
education_map = {
    'Diploma': 1, 
    'High School': 2, 
    'Bachelor': 3, 
    'Master': 4, 
    'PhD': 5
}
company_size_map = {
    'Startup': 1, 
    'Small': 2, 
    'Medium': 3, 
    'Large': 4, 
    'Enterprise': 5
}

df['education_level'] = df['education_level'].map(education_map)
df['company_size'] = df['company_size'].map(company_size_map)

In [ ]:
df_final = pd.get_dummies(df, columns=['job_title', 'industry', 'location', 'remote_work'], drop_first=True)

In [ ]:
df_final = df_final.astype(float)

In [ ]:
df = pd.concat([df, df_final], axis=1)

In [ ]:
df.head()

In [ ]:
df = df.drop(['job_title', 'education_level', 'industry', 'company_size', 'location', 'remote_work'], axis=1)

In [ ]:
df.head()

In [ ]:
numerical_df=df.select_dtypes(include=["int64", "float64"])
corr_matrix=numerical_df.corr()
plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True,
           cmap="coolwarm", fmt=".2f",
           linewidths=.5)
plt.title("correlation heatmap of numericals features", fontsize=15)
plt.savefig("correlation_heatmap.png")

In [ ]:
df.head()

In [ ]:
df = df.loc[:, ~df.columns.duplicated()]

In [ ]:
df.head()

In [ ]:
numerical_cols = ['experience_years', 'skills_count', 'certifications', 'salary']

# Create a figure with subplots
plt.figure(figsize=(15, 10))

for i, col in enumerate(numerical_cols, 1):
    plt.subplot(2, 2, i)
    # y=df[col] creates a vertical box plot
    sns.boxplot(y=df[col], color='skyblue')
    plt.title(f'Box Plot of {col}')

plt.tight_layout()
plt.savefig('numerical_boxplots.png')
plt.show()

In [ ]:
numerical_cols = ['experience_years', 'skills_count', 'certifications', 'salary']

print("--- Outlier Detection Report ---")

for col in numerical_cols:
    # Calculate Q1 (25th percentile) and Q3 (75th percentile)
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    # Calculate the Interquartile Range (IQR)
    IQR = Q3 - Q1
    
    # Define the Upper and Lower Bounds
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    # Count how many values fall outside these bounds
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    count = len(outliers)
    
    print(f"{col}: {count} outliers found")

In [ ]:
df

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition  import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

In [ ]:
X=df.drop('salary', axis=1)
y=df['salary']

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [ ]:
y_train_scaled=np.log1p(y_train)
y_test_scaled=np.log1p(y_test)

In [ ]:
model=RandomForestRegressor(n_estimators=50, max_depth=10, n_jobs=-1)
model.fit(X_train_scaled, y_train_scaled)

In [ ]:
scaled_preds=model.predict(X_test_scaled)
final_preds= np.expm1(scaled_preds)
final_actual=np.expm1(y_test_scaled)

In [ ]:
print(f"real-world mae:{mean_absolute_error(final_actual,final_preds):.2f}")

In [ ]:
r2=r2_score(final_actual,final_preds)
print(f"R2 score:{r2:.4f}")